### ISSUE TITLE
Possible copy/paste error in "Intended Purpose" column for charter items 2&3?

### ISSUE THREAD

**Issue by follower** [OpenCoreVentures/ocv-public-benefit-company#2]
Is the duplication of the "Intended Purpose" cell for [charter items 2 & 3](https://github.com/OpenCoreVentures/ocv-public-benefit-company/blob/main/ocv-public-benefit-company-charter.md) intentional, or a copy-paste error? (Bold emphasis by me.)

| Legal Language      | Intended Purpose |
| ----------- | ----------- |
| 1. [snip] |  [snip]  |
| 2. Release and open source all testing frameworks that the Corporation has created for any feature that we have generally made available to the public under an open-source license;   | **To keep development work open for community review. For example, the open source code base includes a publicly available readme detailing testing frameworks used for each open source feature.**         |
| 3. Not create any constraints and limitations such as repositories, user limits, size, or performance limits to any software projects that the Corporation has generally made available under an open-source license;  | **To keep development work open for community review. For example, the open source code base includes a publicly available readme detailing testing frameworks used for each open source feature.**         |

via here:

https://github.com/OpenCoreVentures/ocv-public-benefit-company/blob/5f0c6c99c07e5bfaa76875c01097e723a172b427/ocv-public-benefit-company-charter.md?plain=1#L8-L9

To me, the "Intended Purpose" given for item 3 didn't seem to be related.

**Comment by OpenCoreVentures** [comment]
Thanks for letting us know! This has been fixed.
